const data = {
  products: [
    {
      _id: '1',
      name: 'Easy Dress',
      category: 'Dresses',
      image: '/img/dress1.png',
      price: 90,
      countInStock: 5,
      brand: 'xmen',
      rating: 4.5,
      reviewNumbers: 3,
      description: 'Quilfied by thekgm',
    },
    {
      _id: '2',
      name: 'Fatih Style 😸',
      category: 'Fatih',
      image: '/img/dress2.png',
      price: 80,
      countInStock: 13,
      brand: 'xmen',
      rating: 4.0,
      reviewNumbers: 2,
      description: 'Quilfied by thekgm',
    },
    {
      _id: '3',
      name: 'Short Pants',
      category: 'Pants',
      image: '/img/dress3.png',
      price: 60,
      countInStock: 17,
      brand: 'xmen',
      rating: 4.8,
      reviewNumbers: 1,
      description: 'Quilfied by thekgm',
    },
    {
      _id: '4',
      name: 'Men Coat',
      category: 'Coat',
      image: '/img/dress4.png',
      price: 120,
      countInStock: 18,
      brand: 'Winter Coats',
      rating: 4.5,
      reviewNumbers: 5,
      description: 'Quilfied by thekgm',
    },
    {
      _id: '5',
      name: 'Casual',
      category: 'Casual',
      image: '/img/dress5.png',
      price: 130,
      countInStock: 20,
      brand: 'Style',
      rating: 4.5,
      reviewNumbers: 6,
      description: 'Quilfied by thekgm',
    },
    {
      _id: '6',
      name: 'Women Short Skirt',
      category: 'Skirt',
      image: '/img/dress6.png',
      price: 400,
      countInStock: 8,
      brand: 'xmen',
      rating: 3.5,
      reviewNumbers: 3,
      description: 'Quilfied by thekgm',
    },
    {
      _id: '7',
      name: 'Fatih Style 😸',
      category: 'Fatih',
      image: '/img/dress7.png',
      price: 400,
      countInStock: 10,
      brand: 'xmen',
      rating: 4.5,
      reviewNumbers: 7,
      description: 'Quilfied by thekgm',
    },
    {
      _id: '8',
      name: 'Wemon Work Dress',
      category: 'work',
      image: '/img/dress8.png',
      price: 400,
      countInStock: 9,
      brand: 'xmen',
      rating: 4.5,
      reviewNumbers: 1,
      description: 'Quilfied by thekgm',
    },
    {
      _id: '9',
      name: 'Maxi Dress',
      category: 'Dress',
      image: '/img/dress9.png',
      price: 400,
      countInStock: 8,
      brand: 'xmen',
      rating: 3,
      reviewNumbers: 6,
      description: 'Quilfied by thekgm',
    },
    {
      _id: '9',
      name: 'Women Casual Dress',
      category: 'casual',
      image: '/img/dress10.png',
      price: 400,
      countInStock: 5,
      brand: 'xmen',
      rating: 4,
      reviewNumbers: 8,
      description: 'Quilfied by thekgm',
    },
  ],
};

export default data;
