const data = {
  products: [
    {
      _id: '1',
      name: 'Women Dress',
      category: 'Dresses',
      image: '/img/dress1.png',
      price: 90,
      brand: 'xmen',
      rating: 4.5,
      numReviews: 10,
      description: 'quilfied by thekgm',
    },
    {
      _id: '2',
      name: 'Women HandBag',
      category: 'Bags',
      image: '/img/dress2.png',
      price: 80,
      brand: 'xmen',
      rating: 4.0,
      numReviews: 10,
      description: 'quilfied by thekgm',
    },
    {
      _id: '3',
      name: 'Women Pants',
      category: 'Pants',
      image: '/img/dress3.png',
      price: 60,
      brand: 'xmen',
      rating: 4.8,
      numReviews: 10,
      description: 'quilfied by thekgm',
    },
    {
      _id: '4',
      name: 'Men Dress',
      category: 'Shirts',
      image: '/img/dress4.png',
      price: 120,
      brand: 'Winter Coats',
      rating: 4.5,
      numReviews: 10,
      description: 'quilfied by thekgm',
    },
    {
      _id: '5',
      name: 'Women Dress',
      category: 'Winter Coats',
      image: '/img/dress5.png',
      price: 130,
      brand: 'Style',
      rating: 4.5,
      numReviews: 10,
      description: 'quilfied by thekgm',
    },
    {
      _id: '6',
      name: 'Men Dress',
      category: 'mystyle',
      image: '/img/dress6.png',
      price: 400,
      brand: 'xmen',
      rating: 4.5,
      numReviews: 10,
      description: 'quilfied by thekgm',
    },
  ],
};

export default data;
